---
- name: " Installing Node-Exporter"
  hosts: amazon
  become: true
  tasks:


  - name: " Installing node-exporter"
    unarchive:
      src: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz"
      dest: "/opt/"
      remote_src: true

  - name: "Copying the files"
    copy:
      src: "/opt/node_exporter-1.3.1.linux-amd64/node_exporter"
      dest: "/usr/local/bin/node_exporter"  
      remote_src: true
      owner: root
      group: root
      mode: 0755

  - name: "Creating systemd service for node-exporter"
    template:
      src: "node_exporter.service.tmp"
      dest: "/etc/systemd/system/node_exporter.service"
      owner: root
      group: root
      mode: 0600


  - name: "configure systemd"
    systemd:
      daemon_reload: true
      enabled: true
      state: started
      name: node_exporter.service
